-- MySQL Script generated by MySQL Workbench
-- Sun 13 Jul 2014 03:41:22 PM WIB
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SiPUS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SiPUS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SiPUS` ;

-- -----------------------------------------------------
-- Table `SiPUS`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(25) NOT NULL,
  `aksi` TEXT NOT NULL,
  `tgl` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_anggota` (
  `no_induk` INT(11) NOT NULL,
  `nama` VARCHAR(50) NOT NULL,
  `kelas` VARCHAR(10) NOT NULL,
  `jurusan` VARCHAR(10) NOT NULL,
  `count` INT(11) NOT NULL DEFAULT '0',
  `denda` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`no_induk`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_buku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_buku` (
  `no` INT(11) NOT NULL AUTO_INCREMENT,
  `kd_buku` VARCHAR(20) NOT NULL,
  `barcode` VARCHAR(20) NOT NULL COMMENT 'ISBN',
  `judul` VARCHAR(200) NOT NULL,
  `pengarang` VARCHAR(50) NOT NULL,
  `thn_terbit` VARCHAR(5) NOT NULL DEFAULT '-',
  `penerbit` VARCHAR(50) NOT NULL,
  `harga` INT(11) NOT NULL,
  `stock` INT(11) NOT NULL,
  `tersedia` INT(11) NOT NULL,
  `count` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`no`))
ENGINE = MyISAM
AUTO_INCREMENT = 2886
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `param` VARCHAR(250) NOT NULL,
  `value` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_kas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_kas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tgl` DATE NOT NULL,
  `ket` TEXT NOT NULL,
  `masuk` INT(11) NOT NULL DEFAULT '0',
  `keluar` INT(11) NOT NULL DEFAULT '0',
  `saldo` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_peminjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_peminjaman` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `siswa` VARCHAR(50) NOT NULL,
  `buku` VARCHAR(50) NOT NULL,
  `tgl_pinjam` DATE NOT NULL,
  `tgl_tempo` DATE NOT NULL,
  `tgl_kembali` DATE NOT NULL,
  `kembali` TINYINT(1) NOT NULL,
  `id_petugas` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 20711
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_pustakawan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_pustakawan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(25) NOT NULL,
  `nama` VARCHAR(100) NOT NULL,
  `kunci` VARCHAR(50) NOT NULL,
  `level` VARCHAR(25) NOT NULL DEFAULT 'Pustakawan',
  `login` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `SiPUS`.`tbl_telat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`tbl_telat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `buku` VARCHAR(50) NULL DEFAULT NULL,
  `induk` INT(10) NOT NULL,
  `siswa` VARCHAR(200) NULL DEFAULT NULL,
  `tanggal` VARCHAR(25) NULL DEFAULT NULL,
  `judul` VARCHAR(300) NULL DEFAULT NULL,
  `kunci` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

USE `SiPUS` ;

-- -----------------------------------------------------
-- Placeholder table for view `SiPUS`.`LAP_PEMINJAMAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiPUS`.`LAP_PEMINJAMAN` (`NO_PEMINJAMAN` INT, `NO_ANGGOTA` INT, `NAMA` INT, `KD_BUKU` INT, `JUDUL_BUKU` INT, `TGL_PINJAM` INT, `JATUH_TEMPO` INT, `TGL_KEMBALI` INT, `KEMBALI` INT, `id_petugas` INT);

-- -----------------------------------------------------
-- View `SiPUS`.`LAP_PEMINJAMAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SiPUS`.`LAP_PEMINJAMAN`;
USE `SiPUS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `SiPUS`.`LAP_PEMINJAMAN` AS select `PINJAM`.`id` AS `NO_PEMINJAMAN`,`PINJAM`.`siswa` AS `NO_ANGGOTA`,`ANGGOTA`.`nama` AS `NAMA`,`PINJAM`.`buku` AS `KD_BUKU`,`BUKU`.`judul` AS `JUDUL_BUKU`,`PINJAM`.`tgl_pinjam` AS `TGL_PINJAM`,`PINJAM`.`tgl_tempo` AS `JATUH_TEMPO`,`PINJAM`.`tgl_kembali` AS `TGL_KEMBALI`,`PINJAM`.`kembali` AS `KEMBALI`,`PINJAM`.`id_petugas` AS `id_petugas` from ((`SiPUS`.`tbl_peminjaman` `PINJAM` join `SiPUS`.`tbl_anggota` `ANGGOTA` on((`PINJAM`.`siswa` = `ANGGOTA`.`no_induk`))) join `SiPUS`.`tbl_buku` `BUKU` on((`PINJAM`.`buku` = `BUKU`.`kd_buku`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
